"""Create tokens

Revision ID: c0a0f7e8f82f
Revises: 
Create Date: 2025-01-21 12:43:26.758872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a0f7e8f82f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('logo_uri', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('daily_volume', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('freeze_authority', sa.String(), nullable=True),
    sa.Column('mint_authority', sa.String(), nullable=True),
    sa.Column('permanent_delegate', sa.String(), nullable=True),
    sa.Column('minted_at', sa.DateTime(), nullable=True),
    sa.Column('extensions', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
